[package]
authors = ["alex <acdenissk69@gmail.com>", "Zeyla Hellyer <hi@zeyla.me>"]
description = "A Rust library for the Discord API."
documentation = "https://docs.rs/serenity"
homepage = "https://github.com/serenity-rs/serenity"
keywords = ["discord", "api"]
license = "ISC"
name = "serenity"
readme = "README.md"
repository = "https://github.com/serenity-rs/serenity.git"
version = "0.8.0"
edition = "2018"

[dependencies]
bitflags = "1"
log = "0.4"
serde_json = "1"
async-trait = "0.1"

[dependencies.static_assertions]
optional = true
version = "1.1"

[dependencies.audiopus]
optional = true
version = "0.2"

[dependencies.command_attr]
path = "./command_attr"
# FIXME: A terrible mistake was done. The version of command_attr
# should've incremented from 0.1.6 to 0.2.0 as 0.1.7 is incompatible
# with serenity 0.7.x, therefore violating the SemVer specification.
# Upon a new release of `command_attr`, please increment to 0.2.0
# and yank 0.1.7 from crates.io.
version = "0.1.7"
optional = true

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.uwl]
optional = true
version = "0.5"

[dependencies.base64]
optional = true
version = "0.11"

[dependencies.byteorder]
optional = true
version = "1"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.flate2]
optional = true
version = "1"

[dependencies.reqwest]
default-features = false
features = ["json", "stream"]
optional = true
version = "0.10"

[dependencies.rand]
optional = true
version = "0.7"

[dependencies.rustls]
optional = true
version = "0.16"

[dependencies.tokio-tls]
optional = true
version = "0.3"

[dependencies.async-tls]
optional = true
version = "0.6"

[dependencies.sodiumoxide]
default-features = false
features = ["std"]
optional = true
version = "0.2"

[dependencies.threadpool]
optional = true
version = "1"

[dependencies.async-tungstenite]
default-features = false
features = ["tokio-runtime"]
optional = true
version = "0.4"

[dependencies.typemap]
optional = true
version = "0.3"

[dependencies.url]
optional = true
version = "^2.1"

[dependencies.bytes]
optional = true
version = "0.5"

[dependencies.webpki]
optional = true
version = "0.21"

[dependencies.webpki-roots]
optional = true
version = "0.19"

[dependencies.tokio]
version = "0.2"
default-features = false
features = ["fs", "macros", "rt-core", "sync", "time", "udp", "process"]

[dependencies.futures]
version = "0.3"

[dev-dependencies.http_crate]
version = "0.2"
package = "http"

[dev-dependencies.matches]
version = "0.1"

[features]
default = [
    "builder",
    "cache",
    "client",
    "framework",
    "gateway",
    "model",
    "http",
    "standard_framework",
    "utils",
    "rustls_backend",
]
default_native_tls = [
    "builder",
    "cache",
    "client",
    "framework",
    "gateway",
    "model",
    "http",
    "standard_framework",
    "utils",
    "native_tls_backend",
]
builder = ["utils"]
cache = []
collector = ["gateway", "model"]
client = [
    "gateway",
    "http",
    "threadpool",
    "typemap",
]
extras = []
framework = ["client", "model", "utils"]
gateway = [
    "flate2",
    "http",
    "url",
    "utils",
]
http = ["url", "bytes"]
absolute_ratelimits = ["http"]
rustls_backend = ["reqwest/rustls-tls", "async-tungstenite/async-tls", "rustls", "webpki", "webpki-roots", "async-tls"]
native_tls_backend = ["reqwest/native-tls", "async-tungstenite/tokio-tls", "tokio-tls"]
model = ["builder", "http"]
standard_framework = ["framework", "uwl", "command_attr", "static_assertions"]
utils = ["base64"]
voice = ["byteorder", "gateway", "audiopus", "rand", "sodiumoxide", "tokio/process"]

[package.metadata.docs.rs]
all-features = true
